services:
  stats-db:
    image: postgres:15
    container_name: stats-db
    environment:
      POSTGRES_DB: statsDB
      POSTGRES_USER: jf76272
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

  stats-service:
    build: ./
    container_name: stats-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/statsDB
      SPRING_DATASOURCE_USERNAME: jf76272
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 8080
      SERVER_ADDRESS: 0.0.0.0
    depends_on:
      - stats-db