apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-service
  template:
    metadata:
      labels:
        app: stats-service
    spec:
      containers:
        - name: stats-service
          image: jf76272/stats-service:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: stats-db-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: statsDB
            - name: DB_USERNAME
              value: jf76272
            - name: DB_PASSWORD
              value: password
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
